services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /home/pi/docker/frigate/config/config.yml:/config/config.yml
      - /home/pi/docker/frigate/volumes/media:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 1935:1935/tcp         # WebRTC over tcp
      - 8554:8554/tcp          # RTSP feeds
      - 8555:8555/tcp         # WebRTC over tcp
      - 8555:8555/udp         # WebRTC over udp
      - 9080:8971/tcp         # WebAccess
    environment:
      FRIGATE_RTSP_PASSWORD: "1234567890"
